# Generated by Django 3.2.5 on 2021-07-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_productfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, verbose_name='Символьный код'),
        ),
    ]
