# Generated by Django 3.2.5 on 2021-07-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Категория'),
        ),
    ]
